# Generated by Django 6.0.6 on 2026-06-30 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(default='Wallet', max_length=40),
        ),
    ]
