# Generated by Django 6.0.6 on 2026-07-20 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
        ('moneyaccounts', '0001_initial'),
        ('transactions', '0003_transaction_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans', to='moneyaccounts.account'),
        ),
        migrations.AddField(
            model_name='loan',
            name='lend_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_as_lend', to='transactions.transaction'),
        ),
        migrations.AddField(
            model_name='loan',
            name='repay_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_as_repay', to='transactions.transaction'),
        ),
    ]
