# Generated by Django 6.0.5 on 2026-07-13 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
