# Generated by Django 6.0.5 on 2026-07-13 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneyaccounts', '0001_initial'),
        ('transactions', '0002_transaction_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='moneyaccounts.account'),
        ),
    ]
