# Generated by Django 6.0.6 on 2026-07-11 01:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('momo', '0001_initial'),
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='momoinboxtoken',
            name='pay_merchant_ussd',
            field=models.CharField(default='*182*8*1*{recipient}*{amount}#', max_length=80),
        ),
        migrations.AddField(
            model_name='momoinboxtoken',
            name='pay_send_ussd',
            field=models.CharField(default='*182*1*1*{recipient}*{amount}#', max_length=80),
        ),
        migrations.CreateModel(
            name='MomoPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(max_length=60)),
                ('recipient_type', models.CharField(choices=[('phone', 'Phone number'), ('merchant', 'Merchant code')], default='phone', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ussd', models.CharField(max_length=120)),
                ('reconciled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('momo_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='momo.momomessage')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='momo_payment', to='transactions.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='momo_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
